name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
    pull_request:
    workflow_dispatch:
    repository_dispatch:
      types:
        - build-repository-dispatch-trigger


jobs:
  pr-verification:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Pull Request Version Validation
        uses: ikmdev/maven-pull-request-version-validation-action@v1.0.0
        
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v4

        
      # If triggered by resository_dispatch then 
      # updates the TINKAR_EXAMPLE_DATA_PROPERTIES_VERSION GitHub Variable
      - name: Update tinkar-example-data-properties version
        if: github.event_name == 'repository_dispatch'
        run: gh variable set TINKAR_EXAMPLE_DATA_PROPERTIES_VERSION --body "${{github.event.client_payload.version}}"
        env:
            GH_TOKEN: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
          
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@v3.3.0
        with:
          branch_name: ${{github.ref_name}}
          mvn_additional_args: -Dtinkar-example-data-properties.version=${{vars.TINKAR_EXAMPLE_DATA_PROPERTIES_VERSION || '1.1.1'}}
         
