name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

# Pipeline/Workflow Triggers
on:
    push:
    pull_request:
    workflow_dispatch:


jobs:
  pr-verification:
    name: Pull Request Validation
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Pull Request Version Validation
        uses: ikmdev/maven-pull-request-version-validation-action@v1.0.0

        
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:      
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-java@v4
        with:
            java-version: '23'
            distribution: 'zulu'

      - name: Get Recent Tag
        id: recent_tag
        run: echo LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`) >> GITHUB_OUTPUT
          
      - name: Build IKM Pipeline
        run: |
          mvn clean install \
          -U \
          -Dtinkar-example-data-properties.version=${{steps.recent_tag.outputs.LATEST_TAG}} \
          -Dmaven.build.cache.skipCache=true 
         