name: Property Dispatch Listener Workflow

run-name: 'Property Dispatch Listener Workflow-- DATA_PROPERTIES_VERSION: ${{github.event.client_payload.version}}'

# Pipeline/Workflow Triggers
on:
    repository_dispatch:
        types:
          - update-repository-dispatch-trigger

env:
  LIST_OF_FILES: "build,post_build,release"

jobs:
    update-job:
        name: Update Environment Property
        runs-on: ubuntu-24.04
        if: github.event_name == 'repository_dispatch' && github.repository_owner == 'ikmdev'
        steps:  
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}

        - name: Update Env
          run: |
                git config user.name "ikmdevops"
                git config user.email 'devops@ikm.dev'
                git pull -p

                # Loop through each file name.
                IFS=',' read -ra files <<< "$FILE_NAMES"

                for file in "${files[@]}"; do
                  echo "Updating DATA_PROPERTIES_VERSION environment to $LATEST_VERSION tag in $file"
                  yq e -i '.env.DATA_PROPERTIES_VERSION = "${{github.event.client_payload.version}}"' .github/workflows/$file.yaml
                  git diff -U1 -w --ignore-blank-lines | grep -E "\-\-\-|[\+\-]\s+DATA_PROPERTIES_VERSION" -B2 -A1| grep -v "^--$"  > update_$file.patch
                  git restore .
                done

                echo "Adding DATA_PROPERTIES_VERSION tag $LATEST_VERSION to choice dropdown for users attempting to generate data"
                yq -i ".on.workflow_dispatch.inputs.properties_version.options = [\"$LATEST_VERSION\"] + .on.workflow_dispatch.inputs.properties_version.options" .github/workflows/generate_data.yaml
                git diff -U1 | grep -E "\-\-\-|\- $LATEST_VERSION" -B2 -A1 | grep -v "^--$" > update_generate_data.patch
                git restore .
                
                git apply *.patch
                git pull -p;
                git commit -am"Updated DATA_PROPERTIES_VERSION environment to $LATEST_VERSION in $FILE_NAMES"
                git push
          env:
              FILE_NAMES: ${{env.LIST_OF_FILES}}
